name: pyEDv1
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy>=1.26.0
  - pandas>=2.2.0
  - scanpy>=1.10.0
  - matplotlib>=3.9.0
  - scipy>=1.13.0
  - statsmodels>=0.14.0
  - numba>=0.60.0
  - tqdm>=4.67.0
  - pip
  - pip:
      # Some packages may need to be installed via pip
      # Add pip-only packages here if needed

